version: '3'
services:
  mongo:
    build: ./mongo
    image: docker_open5gs_mongo
    container_name: mongo
    env_file:
      - .env
    volumes:
      - ./mongo:/mnt/mongo
      - mongodbdata:/var/lib/mongodb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "27017/udp"
      - "27017/tcp"
    networks:
      default:
        ipv4_address: ${MONGO_IP}
  webui:
    build: ./webui
    image: docker_open5gs_webui
    container_name: webui
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - ./webui:/mnt/webui
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "3000/tcp"
    ports:
      - "3000:3000/tcp"
    networks:
      default:
        ipv4_address: ${WEBUI_IP}
  hss:
    build: ./hss
    image: docker_open5gs_hss
    container_name: hss
    env_file:
      - .env
    volumes:
      - ./hss:/mnt/hss
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mongo
    expose:
      - "3868/tcp"
      - "3868/sctp"
      - "5868/tcp"
      - "5868/sctp"
    networks:
      default:
        ipv4_address: ${HSS_IP}
  sgwc:
    build: ./sgwc
    image: docker_open5gs_sgwc
    depends_on:
      - smf
      - upf
    container_name: sgwc
    env_file:
      - .env
    volumes:
      - ./sgwc:/mnt/sgwc
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "2123/udp"
      - "8805/udp"
    networks:
      default:
        ipv4_address: ${SGWC_IP}
  sgwu:
    build: ./sgwu
    image: docker_open5gs_sgwu
    depends_on:
      - smf
      - upf
    container_name: sgwu
    env_file:
      - .env
    volumes:
      - ./sgwu:/mnt/sgwu
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "8805/udp"
      - "2152/udp"
    ports:
      - "${SGWU_ADVERTISE_IP}:2152:2152/udp"
    networks:
      default:
        ipv4_address: ${SGWU_IP}
  smf:
    build: ./smf
    image: docker_open5gs_smf
    container_name: smf
    env_file:
      - .env
    volumes:
      - ./smf:/mnt/smf
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "3868/tcp"
      - "3868/sctp"
      - "5868/tcp"
      - "5868/sctp"
      - "8805/udp"
      - "2123/udp"
      - "7777/tcp"
    networks:
      default:
        ipv4_address: ${SMF_IP}
  upf:
    build: ./upf
    image: docker_open5gs_upf
    depends_on:
      - smf
    container_name: upf
    env_file:
      - .env
    volumes:
      - ./upf:/mnt/upf
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "2152/udp"
      - "8805/udp"
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    # sysctls:
    #   - net.ipv4.ip_forward=1
    #   - net.ipv6.conf.all.disable_ipv6=0
    network_mode: host
  mme:
    build: ./mme
    image: docker_open5gs_mme
    depends_on:
      - hss
      - sgwc
      - sgwu
      - smf
      - upf
    container_name: mme
    env_file:
      - .env
    volumes:
      - ./mme:/mnt/mme
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "3868/tcp"
      - "3868/sctp"
      - "5868/tcp"
      - "5868/sctp"
      - "36412/sctp"
      - "2123/udp"
    ports:
      - "36412:36412/sctp"
    networks:
      default:
        ipv4_address: ${MME_IP}
  pcrf:
    build: ./pcrf
    image: docker_open5gs_pcrf
    container_name: pcrf
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - ./pcrf:/mnt/pcrf
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "${PCRF_BIND_PORT}/tcp"
      - "${PCRF_BIND_PORT}/sctp"
      - "5868/tcp"
      - "5868/sctp"
    ports:
      - "${PCRF_BIND_PORT}:${PCRF_BIND_PORT}/sctp"
      - "${PCRF_BIND_PORT}:${PCRF_BIND_PORT}/tcp"
    networks:
      default:
        ipv4_address: ${PCRF_IP}
  dns:
    build: ./dns
    image: docker_dns
    container_name: dns
    env_file:
      - .env
    volumes:
      - ./dns:/mnt/dns
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "53/udp"
    networks:
      default:
        ipv4_address: ${DNS_IP}
  mysql:
    build: ./mysql
    image: docker_mysql
    container_name: mysql
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "3306/tcp"
    networks:
      default:
        ipv4_address: ${MYSQL_IP}
  fhoss:
    build: ./fhoss
    image: docker_fhoss
    container_name: fhoss
    dns: ${DNS_IP}
    volumes:
      - ./fhoss:/mnt/fhoss
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - dns
      - mysql
    expose:
      - "${FHOSS_BIND_PORT}/tcp"
      - "${FHOSS_BIND_PORT}/sctp"
    ports:
      - "${FHOSS_BIND_PORT}:${FHOSS_BIND_PORT}/sctp"
      - "${FHOSS_BIND_PORT}:${FHOSS_BIND_PORT}/tcp"
      - "8080:8080/tcp"
    networks:
      default:
        ipv4_address: ${FHOSS_IP}
networks:
  default:
    ipam:
      config:
        - subnet: ${TEST_NETWORK}
volumes:
  mongodbdata: {}
  dbdata: {}
